# =========================
# Home Assistant - configuration.yaml
# =========================

# 1) Basis
default_config:

# 2) Frontend thema's
frontend:
  themes: !include_dir_merge_named themes

# 3) YAML-splits
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# 4) HTTP / proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.10 # Nginx Proxy Manager LXC IP

# 5) Command Line — Marstek (altijd geldige JSON)
command_line:
  sensor:
    name: Marstek ES Raw
    command: >-
      bash -lc '
        OUT="$(python3 /config/scripts/marstek_udp_client_all_v3.py --no-pretty --timeout 3 --retries 2 es-mode 2>/dev/null || true)";
        if [ -z "$OUT" ] || ! echo "$OUT" | grep -q "{" ; then
          echo "{\"result\":{}}"
        else
          echo "$OUT"
        fi
      '
    command_timeout: 20
    scan_interval: 30
    value_template: >-
      {% set r = value_json.result if (value_json is defined and value_json.result is defined) else {} %}
      {{ r.state if 'state' in r else 'ok' }}
    json_attributes:
      - result

template:
  - sensor:
      - name: "Marstek Mode"
        state: >
          {% set r = state_attr('sensor.marstek_es_raw','result') %}
          {{ r.mode if r else none }}

      - name: "Marstek Mode Battery SOC"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        state: >
          {% set r = state_attr('sensor.marstek_es_raw','result') %}
          {{ r.bat_soc if r else none }}

      - name: "Marstek On-grid Power"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set r = state_attr('sensor.marstek_es_raw','result') %}
          {{ r.ongrid_power if r else none }}

sensor:
  - platform: integration
    source: sensor.marstek_charge_power
    name: "Marstek Cumulative Energy Charged"
    unit_prefix: k
    round: 3
    method: trapezoidal

  - platform: integration
    source: sensor.marstek_discharge_power
    name: "Marstek Cumulative Energy Discharged"
    unit_prefix: k
    round: 3
    method: trapezoidal

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
