# =========================
# Home Assistant - configuration.yaml
# =========================
homeassistant:
  packages: !include_dir_named packages

# 1) Basis
default_config:

# 2) Frontend thema's
frontend:
  themes: !include_dir_merge_named themes

# 3) YAML-splits
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# 4) HTTP / proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.10 # Nginx Proxy Manager LXC IP

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
